import './globals.css'
import { Cabin } from 'next/font/google'

const cabin = Cabin({ subsets: ['latin'] })

export const metadata = {
  title: 'Movies Jungle',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={cabin.className}>
        <nav className=' mx-9 my-2'> <a href='https://wolmer.me/?utm_source=moviejungle' target='_blank'>By @wolmer</a> </nav>
        {children}
        <p className='text-center '>
        Powered by <a className='text-orange-700' href='themoviedb.org/' target='_blank'>
          the movie db
        </a></p>
        </body>
    </html>
  )
}
